import './global.css';
import { ApolloWrapper } from './ApolloWrapper';

export const metadata = {
  title: 'Welcome to react-monorepo-apollo-cc',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
